### PR TITLE
Update menu design and improve code

### PR DESCRIPTION
**Pull request by danieltj27**
I've updated the menu to make it a bit fancier but also to improve the responsiveness of it as well because the toggle button sits quite small to one side and the menu on mobile hides the sub-menus too.

Overall I've kind of stripped it all out and rebuilt it but still tried to keep true to the design of the site.

I hope you like it 🙂

### CODE REVIEW

**Comment by danieltj27** [comment]
Here is a screen cap of what it now looks like. Don't be afraid to request changes if there's something not right with it. Also please excuse the white page, my phpBBModders demo site is... broken.

phpbbmodders-new-css-menu

**Comment by bonelifer** [comment]
Menu text is a bit small(compare .com/.net). Also now not conforming the the width of the style. Kailey had fixed that in the recent past. Can see below or on http://phpbbmodders.net which uses the same theme with just different gradient as .com. Otherwise I like it. Though @kaileymsnay do you like theme menu coloring(actual menu, not the bar), or maybe needs to be a lighter shade? Much better than the original I found and used from W3Schools, 10 years ago.

menu-redisgn

**Comment by kaileymsnay** [comment]
I like it, just needs to conform to the style width.

> Though @kaileymsnay do you like theme menu coloring(actual menu, not the bar), or maybe needs to be a lighter shade?

I think the coloring is fine. It's close, but not horrible.

**Comment by danieltj27** [comment]
3f53b8c fixes the width of the menu and I've also upped the font size to 12px to match the rest of the style. I think it looks like it fits nicely now. Let me know what you think.

edit:

I also removed the `container` element because it wasn't actually doing anything important. The menu is self contained so removing it lightens the code a bit more.

**Comment by bonelifer** [comment]
Looks good. Checked in FF, Chromium, Vivaldi. If @kaileymsnay is fine with it, we can merge.

**Comment by kaileymsnay** [comment]
This looks good.

**Pull request merged**
